# Generated by Django 4.2.7 on 2023-11-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fueling Date')),
                ('fuel', models.CharField(choices=[('M', 'morning fueling'), ('A', 'afternoon fueling'), ('E', 'evening fueling')], default='E', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Transmission',
        ),
    ]
