# Generated by Django 4.2.7 on 2023-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fueling_delete_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fueling',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='main_app.feature'),
        ),
    ]
